// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yangxj96_serve_example.Repository;

#nullable disable

namespace yangxj96_serve_example.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("yangxj96_serve_example.Model.Demo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Demos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(797),
                            Description = "Description1",
                            IsDeleted = false,
                            Name = "Name1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(807),
                            Description = "Description2",
                            IsDeleted = false,
                            Name = "Name2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(808),
                            Description = "Description3",
                            IsDeleted = false,
                            Name = "Name3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(810),
                            Description = "Description4",
                            IsDeleted = false,
                            Name = "Name4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(811),
                            Description = "Description5",
                            IsDeleted = false,
                            Name = "Name5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(813),
                            Description = "Description6",
                            IsDeleted = false,
                            Name = "Name6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(814),
                            Description = "Description7",
                            IsDeleted = false,
                            Name = "Name7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(849),
                            Description = "Description8",
                            IsDeleted = false,
                            Name = "Name8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(851),
                            Description = "Description9",
                            IsDeleted = false,
                            Name = "Name9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(853),
                            Description = "Description10",
                            IsDeleted = false,
                            Name = "Name10"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(854),
                            Description = "Description11",
                            IsDeleted = false,
                            Name = "Name11"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(855),
                            Description = "Description12",
                            IsDeleted = false,
                            Name = "Name12"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(856),
                            Description = "Description13",
                            IsDeleted = false,
                            Name = "Name13"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(858),
                            Description = "Description14",
                            IsDeleted = false,
                            Name = "Name14"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(859),
                            Description = "Description15",
                            IsDeleted = false,
                            Name = "Name15"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(860),
                            Description = "Description16",
                            IsDeleted = false,
                            Name = "Name16"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(861),
                            Description = "Description17",
                            IsDeleted = false,
                            Name = "Name17"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(863),
                            Description = "Description18",
                            IsDeleted = false,
                            Name = "Name18"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(864),
                            Description = "Description19",
                            IsDeleted = false,
                            Name = "Name19"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(865),
                            Description = "Description20",
                            IsDeleted = false,
                            Name = "Name20"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(866),
                            Description = "Description21",
                            IsDeleted = false,
                            Name = "Name21"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(867),
                            Description = "Description22",
                            IsDeleted = false,
                            Name = "Name22"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(868),
                            Description = "Description23",
                            IsDeleted = false,
                            Name = "Name23"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(869),
                            Description = "Description24",
                            IsDeleted = false,
                            Name = "Name24"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(870),
                            Description = "Description25",
                            IsDeleted = false,
                            Name = "Name25"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(872),
                            Description = "Description26",
                            IsDeleted = false,
                            Name = "Name26"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(873),
                            Description = "Description27",
                            IsDeleted = false,
                            Name = "Name27"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(874),
                            Description = "Description28",
                            IsDeleted = false,
                            Name = "Name28"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(875),
                            Description = "Description29",
                            IsDeleted = false,
                            Name = "Name29"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(876),
                            Description = "Description30",
                            IsDeleted = false,
                            Name = "Name30"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(877),
                            Description = "Description31",
                            IsDeleted = false,
                            Name = "Name31"
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(878),
                            Description = "Description32",
                            IsDeleted = false,
                            Name = "Name32"
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(879),
                            Description = "Description33",
                            IsDeleted = false,
                            Name = "Name33"
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(880),
                            Description = "Description34",
                            IsDeleted = false,
                            Name = "Name34"
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(881),
                            Description = "Description35",
                            IsDeleted = false,
                            Name = "Name35"
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(883),
                            Description = "Description36",
                            IsDeleted = false,
                            Name = "Name36"
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(884),
                            Description = "Description37",
                            IsDeleted = false,
                            Name = "Name37"
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(885),
                            Description = "Description38",
                            IsDeleted = false,
                            Name = "Name38"
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(886),
                            Description = "Description39",
                            IsDeleted = false,
                            Name = "Name39"
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(887),
                            Description = "Description40",
                            IsDeleted = false,
                            Name = "Name40"
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(888),
                            Description = "Description41",
                            IsDeleted = false,
                            Name = "Name41"
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(889),
                            Description = "Description42",
                            IsDeleted = false,
                            Name = "Name42"
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(890),
                            Description = "Description43",
                            IsDeleted = false,
                            Name = "Name43"
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(891),
                            Description = "Description44",
                            IsDeleted = false,
                            Name = "Name44"
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(892),
                            Description = "Description45",
                            IsDeleted = false,
                            Name = "Name45"
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(893),
                            Description = "Description46",
                            IsDeleted = false,
                            Name = "Name46"
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(894),
                            Description = "Description47",
                            IsDeleted = false,
                            Name = "Name47"
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(895),
                            Description = "Description48",
                            IsDeleted = false,
                            Name = "Name48"
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(896),
                            Description = "Description49",
                            IsDeleted = false,
                            Name = "Name49"
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(897),
                            Description = "Description50",
                            IsDeleted = false,
                            Name = "Name50"
                        },
                        new
                        {
                            Id = 51,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(898),
                            Description = "Description51",
                            IsDeleted = false,
                            Name = "Name51"
                        },
                        new
                        {
                            Id = 52,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(899),
                            Description = "Description52",
                            IsDeleted = false,
                            Name = "Name52"
                        },
                        new
                        {
                            Id = 53,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(900),
                            Description = "Description53",
                            IsDeleted = false,
                            Name = "Name53"
                        },
                        new
                        {
                            Id = 54,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(901),
                            Description = "Description54",
                            IsDeleted = false,
                            Name = "Name54"
                        },
                        new
                        {
                            Id = 55,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(902),
                            Description = "Description55",
                            IsDeleted = false,
                            Name = "Name55"
                        },
                        new
                        {
                            Id = 56,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(903),
                            Description = "Description56",
                            IsDeleted = false,
                            Name = "Name56"
                        },
                        new
                        {
                            Id = 57,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(904),
                            Description = "Description57",
                            IsDeleted = false,
                            Name = "Name57"
                        },
                        new
                        {
                            Id = 58,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(926),
                            Description = "Description58",
                            IsDeleted = false,
                            Name = "Name58"
                        },
                        new
                        {
                            Id = 59,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(927),
                            Description = "Description59",
                            IsDeleted = false,
                            Name = "Name59"
                        },
                        new
                        {
                            Id = 60,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(928),
                            Description = "Description60",
                            IsDeleted = false,
                            Name = "Name60"
                        },
                        new
                        {
                            Id = 61,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(929),
                            Description = "Description61",
                            IsDeleted = false,
                            Name = "Name61"
                        },
                        new
                        {
                            Id = 62,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(930),
                            Description = "Description62",
                            IsDeleted = false,
                            Name = "Name62"
                        },
                        new
                        {
                            Id = 63,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(931),
                            Description = "Description63",
                            IsDeleted = false,
                            Name = "Name63"
                        },
                        new
                        {
                            Id = 64,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(932),
                            Description = "Description64",
                            IsDeleted = false,
                            Name = "Name64"
                        },
                        new
                        {
                            Id = 65,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(933),
                            Description = "Description65",
                            IsDeleted = false,
                            Name = "Name65"
                        },
                        new
                        {
                            Id = 66,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(935),
                            Description = "Description66",
                            IsDeleted = false,
                            Name = "Name66"
                        },
                        new
                        {
                            Id = 67,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(937),
                            Description = "Description67",
                            IsDeleted = false,
                            Name = "Name67"
                        },
                        new
                        {
                            Id = 68,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(938),
                            Description = "Description68",
                            IsDeleted = false,
                            Name = "Name68"
                        },
                        new
                        {
                            Id = 69,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(939),
                            Description = "Description69",
                            IsDeleted = false,
                            Name = "Name69"
                        },
                        new
                        {
                            Id = 70,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(940),
                            Description = "Description70",
                            IsDeleted = false,
                            Name = "Name70"
                        },
                        new
                        {
                            Id = 71,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(941),
                            Description = "Description71",
                            IsDeleted = false,
                            Name = "Name71"
                        },
                        new
                        {
                            Id = 72,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(942),
                            Description = "Description72",
                            IsDeleted = false,
                            Name = "Name72"
                        },
                        new
                        {
                            Id = 73,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(943),
                            Description = "Description73",
                            IsDeleted = false,
                            Name = "Name73"
                        },
                        new
                        {
                            Id = 74,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(944),
                            Description = "Description74",
                            IsDeleted = false,
                            Name = "Name74"
                        },
                        new
                        {
                            Id = 75,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(945),
                            Description = "Description75",
                            IsDeleted = false,
                            Name = "Name75"
                        },
                        new
                        {
                            Id = 76,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(946),
                            Description = "Description76",
                            IsDeleted = false,
                            Name = "Name76"
                        },
                        new
                        {
                            Id = 77,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(947),
                            Description = "Description77",
                            IsDeleted = false,
                            Name = "Name77"
                        },
                        new
                        {
                            Id = 78,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(948),
                            Description = "Description78",
                            IsDeleted = false,
                            Name = "Name78"
                        },
                        new
                        {
                            Id = 79,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(949),
                            Description = "Description79",
                            IsDeleted = false,
                            Name = "Name79"
                        },
                        new
                        {
                            Id = 80,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(950),
                            Description = "Description80",
                            IsDeleted = false,
                            Name = "Name80"
                        },
                        new
                        {
                            Id = 81,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(951),
                            Description = "Description81",
                            IsDeleted = false,
                            Name = "Name81"
                        },
                        new
                        {
                            Id = 82,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(952),
                            Description = "Description82",
                            IsDeleted = false,
                            Name = "Name82"
                        },
                        new
                        {
                            Id = 83,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(953),
                            Description = "Description83",
                            IsDeleted = false,
                            Name = "Name83"
                        },
                        new
                        {
                            Id = 84,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(954),
                            Description = "Description84",
                            IsDeleted = false,
                            Name = "Name84"
                        },
                        new
                        {
                            Id = 85,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(955),
                            Description = "Description85",
                            IsDeleted = false,
                            Name = "Name85"
                        },
                        new
                        {
                            Id = 86,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(957),
                            Description = "Description86",
                            IsDeleted = false,
                            Name = "Name86"
                        },
                        new
                        {
                            Id = 87,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(958),
                            Description = "Description87",
                            IsDeleted = false,
                            Name = "Name87"
                        },
                        new
                        {
                            Id = 88,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(959),
                            Description = "Description88",
                            IsDeleted = false,
                            Name = "Name88"
                        },
                        new
                        {
                            Id = 89,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(960),
                            Description = "Description89",
                            IsDeleted = false,
                            Name = "Name89"
                        },
                        new
                        {
                            Id = 90,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(961),
                            Description = "Description90",
                            IsDeleted = false,
                            Name = "Name90"
                        },
                        new
                        {
                            Id = 91,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(962),
                            Description = "Description91",
                            IsDeleted = false,
                            Name = "Name91"
                        },
                        new
                        {
                            Id = 92,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(963),
                            Description = "Description92",
                            IsDeleted = false,
                            Name = "Name92"
                        },
                        new
                        {
                            Id = 93,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(964),
                            Description = "Description93",
                            IsDeleted = false,
                            Name = "Name93"
                        },
                        new
                        {
                            Id = 94,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(965),
                            Description = "Description94",
                            IsDeleted = false,
                            Name = "Name94"
                        },
                        new
                        {
                            Id = 95,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(966),
                            Description = "Description95",
                            IsDeleted = false,
                            Name = "Name95"
                        },
                        new
                        {
                            Id = 96,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(967),
                            Description = "Description96",
                            IsDeleted = false,
                            Name = "Name96"
                        },
                        new
                        {
                            Id = 97,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(968),
                            Description = "Description97",
                            IsDeleted = false,
                            Name = "Name97"
                        },
                        new
                        {
                            Id = 98,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(969),
                            Description = "Description98",
                            IsDeleted = false,
                            Name = "Name98"
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2023, 3, 8, 1, 50, 52, 311, DateTimeKind.Local).AddTicks(970),
                            Description = "Description99",
                            IsDeleted = false,
                            Name = "Name99"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
